filter:
    paths: [src/*]
    excluded_paths: [vendor/*, tests/*, app/*, bin/*, library/*, support/*]

tools:
    php_mess_detector: true
    php_analyzer: true
    php_code_sniffer:
        config:
            standard: PSR2
            sniffs: { psr1: { classes: { class_declaration_sniff: true } } }
        filter:
            excluded_paths: [vendor/*, tests/* app/*, bin/*, support/*, doc/*]
    sensiolabs_security_checker: true
    php_cpd: true
    php_loc: true
    php_pdepend: true
    external_code_coverage: true
