language: php
php:
  - "5.4"
  - "5.3"

before_script:
  - cp app/config/parameters.yml-dist app/config/parameters.yml
  - php bin/composer.phar install --prefer-source --dev
  - pear install pear/PHP_CodeSniffer
  - phpenv rehash

script: phpunit --coverage-text --coverage-clover=coverage.clover

after_script:
  - phpcs --report=full --report=gitblame --standard=PSR2 src/

after_success:
    - wget https://scrutinizer-ci.com/ocular.phar
    - php ocular.phar code-coverage:upload --format=php-clover coverage.clover

notifications:
  irc:
    - "irc.freenode.org#protalk"
