ProtalkAdminBundle:
    resource: "@ProtalkAdminBundle/Controller/"
    type:     annotation
    prefix:   /

ProtalkMediaBundle:
    resource: "@ProtalkMediaBundle/Controller/"
    type:     annotation
    prefix:   /

ProtalkPageBundle:
    resource: "@ProtalkPageBundle/Controller/"
    type:     annotation
    prefix:   /page

ProtalkApiBundle:
    resource: "@ProtalkApiBundle/Controller/"
    type:     annotation
    prefix:   /api

ProtalkUserBundle:
    resource: "@ProtalkUserBundle/Controller/"
    type:     annotation
    prefix:   /

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"
    prefix: /user

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /user/register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /user/resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /user/change-password

admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin

sonata_user:
    resource: '@SonataUserBundle/Resources/config/routing/admin_security.xml'
    prefix: /admin

sonata_user_profile:
    resource: "@SonataUserBundle/Resources/config/routing/profile.xml"
    prefix: /user/profile

# Internal routing configuration to handle ESI
#_internal:
#   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#   prefix:   /_internal